# Generated by Django 5.1.4 on 2025-01-17 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_skill'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Skill',
        ),
    ]
