# Generated by Django 5.1.4 on 2025-04-11 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_customuser_options_customuser_account_type_and_more'),
        ('accounts', '0006_customuser_bio_customuser_location'),
    ]

    operations = [
    ]
