# Generated by Django 4.2.20 on 2025-05-23 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_usersession"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersession",
            name="device_fingerprint",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="usersession",
            name="ip_address",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="usersession",
            name="user_agent",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddIndex(
            model_name="usersession",
            index=models.Index(
                fields=["user", "is_active"], name="accounts_us_user_id_91ed82_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="usersession",
            index=models.Index(
                fields=["last_activity"], name="accounts_us_last_ac_a630f7_idx"
            ),
        ),
    ]
