# Generated by Django 5.1.4 on 2025-01-17 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_post_content_comment_report_share_favorite_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('blog', 'Blog'), ('news', 'News'), ('review', 'Review')], max_length=10),
        ),
    ]
