# Generated by Django 5.1.4 on 2025-02-25 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_post_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('blog', 'Blog'), ('news', 'News'), ('review', 'Review'), ('text', 'Text'), ('image', 'Image'), ('video', 'Video')], max_length=10),
        ),
    ]
