# Generated by Django 4.2.20 on 2025-04-27 18:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("posts", "0005_alter_post_post_type"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comment",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="favorite",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="like",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="post",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="report",
            options={"ordering": ["-reported_at"]},
        ),
        migrations.AlterModelOptions(
            name="save",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="share",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddField(
            model_name="comment",
            name="is_edited",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="comment",
            name="likes",
            field=models.ManyToManyField(
                blank=True, related_name="liked_comments", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="comment",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="replies",
                to="posts.comment",
            ),
        ),
        migrations.AddField(
            model_name="comment",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="favorite",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="like",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="post",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="post_images/"),
        ),
        migrations.AddField(
            model_name="post",
            name="is_edited",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="post",
            name="is_pinned",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="post",
            name="likes",
            field=models.ManyToManyField(
                blank=True, related_name="liked_posts", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="shares",
            field=models.ManyToManyField(
                blank=True, related_name="shared_posts", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="visibility",
            field=models.CharField(
                choices=[
                    ("Public", "Public"),
                    ("Connections", "Connections"),
                    ("Private", "Private"),
                ],
                default="Public",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="report",
            name="is_resolved",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="save",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="share",
            name="content",
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="share",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="comment",
            name="content",
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name="like",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="post_likes",
                to="posts.post",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="post_type",
            field=models.CharField(
                choices=[
                    ("post", "Post"),
                    ("article", "Article"),
                    ("project", "Project"),
                    ("job", "Job"),
                    ("service", "Service"),
                ],
                default="post",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="share",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="post_shares",
                to="posts.post",
            ),
        ),
    ]
