# Generated by Django 4.2.20 on 2025-06-07 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0006_alter_comment_options_alter_favorite_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comment",
            options={},
        ),
        migrations.AlterModelOptions(
            name="favorite",
            options={},
        ),
        migrations.AlterModelOptions(
            name="like",
            options={},
        ),
        migrations.AlterModelOptions(
            name="post",
            options={},
        ),
        migrations.AlterModelOptions(
            name="report",
            options={},
        ),
        migrations.AlterModelOptions(
            name="save",
            options={},
        ),
        migrations.AlterModelOptions(
            name="share",
            options={},
        ),
        migrations.RemoveField(
            model_name="comment",
            name="is_edited",
        ),
        migrations.RemoveField(
            model_name="comment",
            name="likes",
        ),
        migrations.RemoveField(
            model_name="comment",
            name="parent",
        ),
        migrations.RemoveField(
            model_name="comment",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="favorite",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="like",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="post",
            name="image",
        ),
        migrations.RemoveField(
            model_name="post",
            name="is_edited",
        ),
        migrations.RemoveField(
            model_name="post",
            name="is_pinned",
        ),
        migrations.RemoveField(
            model_name="post",
            name="likes",
        ),
        migrations.RemoveField(
            model_name="post",
            name="shares",
        ),
        migrations.RemoveField(
            model_name="post",
            name="visibility",
        ),
        migrations.RemoveField(
            model_name="report",
            name="is_resolved",
        ),
        migrations.RemoveField(
            model_name="save",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="share",
            name="content",
        ),
        migrations.RemoveField(
            model_name="share",
            name="created_at",
        ),
        migrations.AlterField(
            model_name="comment",
            name="content",
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name="like",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="likes",
                to="posts.post",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="post_type",
            field=models.CharField(
                choices=[
                    ("blog", "Blog"),
                    ("news", "News"),
                    ("review", "Review"),
                    ("text", "Text"),
                    ("image", "Image"),
                    ("video", "Video"),
                ],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="share",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shares",
                to="posts.post",
            ),
        ),
    ]
