# Generated by Django 4.2.20 on 2025-06-26 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0008_post_image_post_is_edited_post_is_pinned_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="content",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="post",
            name="post_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("blog", "Blog"),
                    ("news", "News"),
                    ("review", "Review"),
                    ("text", "Text"),
                    ("image", "Image"),
                    ("video", "Video"),
                ],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="title",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
