# Generated by Django 5.1.4 on 2025-01-08 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_post_content_comment_report_share_favorite_and_more'),
        ('profiles', '0002_profile_education_profile_experience_profile_skills_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['-last_active'], 'verbose_name': 'Profile', 'verbose_name_plural': 'Profiles'},
        ),
        migrations.RemoveField(
            model_name='profile',
            name='education',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='experience',
        ),
        migrations.AddField(
            model_name='profile',
            name='account_status',
            field=models.CharField(choices=[('active', 'Active'), ('deactivated', 'Deactivated'), ('suspended', 'Suspended')], default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='blocked_users',
            field=models.ManyToManyField(related_name='blocked_by', to='profiles.profile'),
        ),
        migrations.AddField(
            model_name='profile',
            name='close_friends',
            field=models.ManyToManyField(related_name='close_friend_of', to='profiles.profile'),
        ),
        migrations.AddField(
            model_name='profile',
            name='display_name',
            field=models.CharField(default='New User', max_length=100, verbose_name='Display Name'),
        ),
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(db_index=True, default='default@example.com', max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='followers',
            field=models.ManyToManyField(related_name='following', to='profiles.profile'),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_active',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='liked_posts',
            field=models.ManyToManyField(related_name='liked_by', to='posts.post'),
        ),
        migrations.AddField(
            model_name='profile',
            name='notification_settings',
            field=models.JSONField(blank=True, default=dict, help_text='Notification settings.'),
        ),
        migrations.AddField(
            model_name='profile',
            name='password',
            field=models.CharField(default='changeme123', help_text='Mandatory password for the user.', max_length=128),
        ),
        migrations.AddField(
            model_name='profile',
            name='posts',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='authorProfile', to='posts.post'),
        ),
        migrations.AddField(
            model_name='profile',
            name='privacy_settings',
            field=models.JSONField(blank=True, default=dict, help_text='Privacy settings.'),
        ),
        migrations.AddField(
            model_name='profile',
            name='security_settings',
            field=models.JSONField(blank=True, default=dict, help_text='Security settings.'),
        ),
        migrations.AddField(
            model_name='profile',
            name='username',
            field=models.CharField(db_index=True, default='default_user', max_length=30, unique=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='website',
            field=models.URLField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='skills',
            field=models.JSONField(blank=True, default=dict, editable=False, help_text='This field is managed by AI'),
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(default='', max_length=200, verbose_name='School Name')),
                ('degree', models.CharField(default='', max_length=100)),
                ('field_of_study', models.CharField(default='', max_length=100)),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True, default='', null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education_details', to='profiles.profile')),
            ],
            options={
                'verbose_name': 'Education',
                'verbose_name_plural': 'Education',
                'ordering': ['-end_date', '-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=200)),
                ('company', models.CharField(default='', max_length=200)),
                ('location', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, default='', null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='profiles.profile')),
            ],
            options={
                'verbose_name': 'Experience',
                'verbose_name_plural': 'Experiences',
                'ordering': ['-end_date', '-start_date'],
            },
        ),
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('issuing_organization', models.CharField(default='', max_length=200)),
                ('issue_date', models.DateField(null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('credential_id', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('credential_url', models.URLField(blank=True, default='', null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='licenses', to='profiles.profile')),
            ],
            options={
                'verbose_name': 'License',
                'verbose_name_plural': 'Licenses',
                'ordering': ['-issue_date'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=200)),
                ('description', models.TextField(default='')),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('url', models.URLField(blank=True, default='', null=True)),
                ('is_research', models.BooleanField(default=False)),
                ('collaborators', models.ManyToManyField(blank=True, related_name='collaborated_projects', to='profiles.profile')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='profiles.profile')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ['-end_date', '-start_date'],
            },
        ),
    ]
