# Generated by Django 4.2.20 on 2025-06-07 08:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("profiles", "0004_alter_profile_options_remove_profile_password_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="username",
        ),
        migrations.AlterField(
            model_name="profile",
            name="notification_settings",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="profile",
            name="privacy_settings",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="profile",
            name="security_settings",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="profile",
            name="skills",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="profile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
