# Generated by Django 4.2.20 on 2025-06-24 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0005_remove_profile_username_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="profile_image",
            field=models.ImageField(
                blank=True,
                help_text="Main profile image for the user",
                null=True,
                upload_to="profile_images/",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="skills",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="AI-generated skills - read-only for users",
            ),
        ),
    ]
