# Generated by Django 4.2.20 on 2025-06-25 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0006_profile_profile_image_alter_profile_skills"),
    ]

    operations = []
