# Generated by Django 4.2.20 on 2025-06-25 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0007_add_followers_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="project_image",
            field=models.ImageField(
                blank=True,
                help_text="Project screenshot or image",
                null=True,
                upload_to="project_images/",
            ),
        ),
    ]
