# Generated by Django 5.1.4 on 2025-06-25 16:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0008_project_project_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="followers",
        ),
        migrations.AddField(
            model_name="profile",
            name="is_private",
            field=models.BooleanField(default=False),
        ),
    ]
