# Generated by Django 4.2.20 on 2025-06-26 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0009_remove_profile_followers_profile_is_private"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="posts",
        ),
    ]
